### PR TITLE
read file without storing sheets in memory

### PR DESCRIPTION
**Pull request by achekanov**
I needed a possibility to read and process **very** large files without storing them in memory (stream reading rows of data). The proposed changes provide this possibility using callback function. Could you review them and if possible merge and update the npm?
Thank you.

### CODE REVIEW

**Comment by gutkyu** [comment]
> I needed a possibility to read and process **very** large files without storing them in memory (stream reading rows of data). The proposed changes provide this possibility using callback function. Could you review them and if possible merge and update the npm?
> Thank you.

Hi, achekanov.
Thanks  for your code.
I think more modifications are needed to handle very large files without storing them in memory.
The function sheet() just parses the sheet raw memory buffer already loaded from the xls file.
To solve this problem, I thought that asynchronous method should be applied to parsing, so I made 'async' branch and worked on it.
But there were many complicated problems, so I couldn't finish it.
I will update it when it is resolved.

Thank you.

**Comment by gutkyu** [comment]
> I needed a possibility to read and process **very** large files without storing them in memory (stream reading rows of data). The proposed changes provide this possibility using callback function. Could you review them and if possible merge and update the npm?
> Thank you.

**Comment by gutkyu** [comment]
> I needed a possibility to read and process **very** large files without storing them in memory (stream reading rows of data). The proposed changes provide this possibility using callback function. Could you review them and if possible merge and update the npm?
> Thank you.

I released [v1.0.0-rc.x](https://github.com/gutkyu/node-xlrd/tree/main_v1) and hope this will help you.

**Comment by achekanov** [comment]
Thank you, will give it a try.

**Pull request closed without merging**
